workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build appbundle

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk